### ISSUE TITLE
use 'resque' logger

### ISSUE THREAD

**Issue by twelvelabs** [gocardless/resque-sentry#1]
Would you be interested in a pull request that sets the logger value to "resque" when sending the exception? My team would like to be able to filter all errors that came from resque.

**Comment by hmarr** [comment]
This could be useful. Another option would be to use [tags](https://www.getsentry.com/docs/tags/) for this. Thoughts?

**Comment by twelvelabs** [comment]
If I understand Sentry's implementation correctly, the logger value is actually just a pre-defined tag (same as server, os, browser, etc...). One could set `Raven.tags_context('logger' => 'resque')`, but I'm not sure that would override the 'root' logger value that's set by default.

The benefit of using logger (vs some other tag) is that it's shown in the error list at the bottom of each item.

How about I make it default to 'root', but you can change it via something like

`Resque::Failure::Sentry.logger = 'resque'`

I'll put together a pull request and send it your way.

**Comment by hmarr** [comment]
Sounds great, thanks.
